version: '3'

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
      #No need to expose the port, as it is only accessible from the host machine
      # ports:
      #   - "27017:27017"
    restart: always # Restart the container if it crashes
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: [ "--auth" ]

  mongo_express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
    ports:
      - "8080:8081"
    restart: always

  poke-app:
    depends_on:
      - db
      - mongo_express
    image: klerith/pokemon-nest-app:1.0.0
    ports:
      - "3000:3000"
    environment:
      - MONGODB=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017
      - DB_NAME=${MONGO_DB_NAME}
    restart: always
volumes:
  poke-vol:
    external: false
