#VERSION DEL DOCKER COMPOSE
version: '3'
#SERVICIOS QUE SE VAN A EJECUTAR
services:
  #Se coloca el nombre del servicio
  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      #bind volume
      - ./postgres:/var/lib/postgresql/data
    #- postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456

#VOLUMENES QUE SE VAN A USAR/CREAR
# volumes:
#   postgres-db:
#     external: true

#DOCKER COMPOSE DOWN EN CASO DE QUE SE QUIERA ELIMINAR LOS CONTENEDORES Y VOLUMENES PARA VOLVER A CREARLOS
